/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package frontend;

import backend.Employees;
import java.util.ArrayList;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Jorgen
 */
public class addEmployeeFrame extends javax.swing.JFrame {
    private int caseId;
    private Employees employees;

    /**
     * Creates new form addEmployeeFrame
     */
    public addEmployeeFrame(int caseId) {
        this.caseId = caseId;
        this.employees = new Employees();
        initComponents();
    }

    public JTable getTableLeft() {
        return tableLeft;
    }

    public JTable getTableRight() {
        return tableRight;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelLeft = new javax.swing.JPanel();
        tableNotAttending = new javax.swing.JScrollPane();
        tableLeft = new javax.swing.JTable();
        panelCenter = new javax.swing.JPanel();
        buttonAddToCase = new javax.swing.JButton();
        buttonRemoveFromCase = new javax.swing.JButton();
        buttonRegisterNewEmployer = new javax.swing.JButton();
        buttonFinish = new javax.swing.JButton();
        panelRight = new javax.swing.JPanel();
        tableAttending = new javax.swing.JScrollPane();
        tableRight = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setLayout(new java.awt.BorderLayout());

        panelLeft.setPreferredSize(new java.awt.Dimension(425, 690));
        panelLeft.setLayout(new javax.swing.BoxLayout(panelLeft, javax.swing.BoxLayout.LINE_AXIS));

        tableLeft.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Fornavn", "Etternavn", "Sist reg", "Ant uten"
            }
        ));
        tableNotAttending.setViewportView(tableLeft);

        panelLeft.add(tableNotAttending);

        jPanel1.add(panelLeft, java.awt.BorderLayout.WEST);

        panelCenter.setBackground(new java.awt.Color(153, 153, 153));
        panelCenter.setPreferredSize(new java.awt.Dimension(174, 690));

        buttonAddToCase.setFont(new java.awt.Font("Optima", 1, 18)); // NOI18N
        buttonAddToCase.setText("->");
        buttonAddToCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddToCaseActionPerformed(evt);
            }
        });

        buttonRemoveFromCase.setFont(new java.awt.Font("Optima", 1, 18)); // NOI18N
        buttonRemoveFromCase.setText("<-");
        buttonRemoveFromCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveFromCaseActionPerformed(evt);
            }
        });

        buttonRegisterNewEmployer.setFont(new java.awt.Font("Optima", 1, 14)); // NOI18N
        buttonRegisterNewEmployer.setText("Registrer ny person");
        buttonRegisterNewEmployer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegisterNewEmployerActionPerformed(evt);
            }
        });

        buttonFinish.setFont(new java.awt.Font("Optima", 1, 18)); // NOI18N
        buttonFinish.setText("Ferdig");
        buttonFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFinishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCenterLayout = new javax.swing.GroupLayout(panelCenter);
        panelCenter.setLayout(panelCenterLayout);
        panelCenterLayout.setHorizontalGroup(
            panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCenterLayout.createSequentialGroup()
                .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCenterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonRegisterNewEmployer))
                    .addGroup(panelCenterLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(buttonAddToCase, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCenterLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(buttonRemoveFromCase, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCenterLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(buttonFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        panelCenterLayout.setVerticalGroup(
            panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCenterLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(buttonAddToCase, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(buttonRegisterNewEmployer, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(buttonRemoveFromCase, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(buttonFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(panelCenter, java.awt.BorderLayout.CENTER);

        panelRight.setPreferredSize(new java.awt.Dimension(425, 690));
        panelRight.setLayout(new javax.swing.BoxLayout(panelRight, javax.swing.BoxLayout.LINE_AXIS));

        tableRight.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Fornavn", "Etternavn", "Sist reg", "Ant uten"
            }
        ));
        tableAttending.setViewportView(tableRight);

        panelRight.add(tableAttending);

        jPanel1.add(panelRight, java.awt.BorderLayout.EAST);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddToCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddToCaseActionPerformed
        int employeeId = (int)tableLeft.getValueAt(tableLeft.getSelectedRow(), 0);
        employees.addToCase(caseId, employeeId);  
        employees.updateEmployeeAvailable(tableLeft, tableRight, caseId);
    }//GEN-LAST:event_buttonAddToCaseActionPerformed

    private void buttonRemoveFromCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveFromCaseActionPerformed
//        String firstName = (String)tableRight.getModel().getValueAt(tableRight.getSelectedRow(), 1);
//        String lastName = (String)tableRight.getModel().getValueAt(tableRight.getSelectedRow(), 2);
//        this.employees.moveToNotAttended(firstName, lastName, tableLeft, tableRight);
    }//GEN-LAST:event_buttonRemoveFromCaseActionPerformed

    private void buttonRegisterNewEmployerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegisterNewEmployerActionPerformed
//        ArrayList<Integer> errors = new ArrayList<Integer>();
//        JTextField textfieldFirstName = new JTextField(5);
//        JTextField textfieldLastName = new JTextField(5);
//        JPanel panelNewEmployee = new JPanel();
//        panelNewEmployee.add(new JLabel("Fornavn:"));
//        panelNewEmployee.add(textfieldFirstName);
//        panelNewEmployee.add(Box.createHorizontalStrut(15));
//        panelNewEmployee.add(new JLabel("Etternavn:"));
//        panelNewEmployee.add(textfieldLastName);
//
//        int result = JOptionPane.showConfirmDialog(null, panelNewEmployee,
//            "Skriv inn fornavn og etternavn", JOptionPane.OK_CANCEL_OPTION);
//        if (result == JOptionPane.OK_OPTION) {
//            errors = this.employees.createEmployee(
//                textfieldFirstName.getText().trim(), textfieldLastName.getText().trim());
//            this.employees.updateGUILists(tableLeft, tableRight);
//        }
//        if(!errors.isEmpty()){
//            showMessageDialog(null, "FEIL: Databasen ikke oppdatert");
//        }
//        else{
//            System.out.println("WOHOOOOO");
//        }
    }//GEN-LAST:event_buttonRegisterNewEmployerActionPerformed

    private void buttonFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFinishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonFinishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(final int caseId) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addEmployeeFrame(caseId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddToCase;
    private javax.swing.JButton buttonFinish;
    private javax.swing.JButton buttonRegisterNewEmployer;
    private javax.swing.JButton buttonRemoveFromCase;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JPanel panelRight;
    private javax.swing.JScrollPane tableAttending;
    private javax.swing.JTable tableLeft;
    private javax.swing.JScrollPane tableNotAttending;
    private javax.swing.JTable tableRight;
    // End of variables declaration//GEN-END:variables
}
