/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package frontend;

import backend.Employees;
import java.util.ArrayList;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Jorgen
 */
public class addEmployeeFrame extends javax.swing.JFrame {
    private int caseId;
    private Employees employees;

    /**
     * Creates new form addEmployeeFrame
     */
    public addEmployeeFrame(int caseId) {
        this.caseId = caseId;
        this.employees = new Employees();
        initComponents();
        this.employees.updateEmployeeAvailable(tableLeft, tableRight, this.caseId);        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        panelNorth = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelCenter = new javax.swing.JPanel();
        panelCenterLeft = new javax.swing.JPanel();
        tableNotAttending = new javax.swing.JScrollPane();
        tableLeft = new javax.swing.JTable();
        panelCenterCenter = new javax.swing.JPanel();
        buttonAddToCase = new javax.swing.JButton();
        buttonRemoveFromCase = new javax.swing.JButton();
        buttonFinish = new javax.swing.JButton();
        panelCenterRight = new javax.swing.JPanel();
        tableAttending = new javax.swing.JScrollPane();
        tableRight = new javax.swing.JTable();
        panelSouth = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 204));
        setMaximumSize(new java.awt.Dimension(1024, 706));
        setMinimumSize(new java.awt.Dimension(1024, 706));
        setPreferredSize(new java.awt.Dimension(1024, 706));

        panelBackground.setBackground(new java.awt.Color(255, 255, 0));
        panelBackground.setMaximumSize(new java.awt.Dimension(1024, 706));
        panelBackground.setMinimumSize(new java.awt.Dimension(1024, 706));
        panelBackground.setPreferredSize(new java.awt.Dimension(1024, 706));
        panelBackground.setSize(new java.awt.Dimension(1024, 706));
        panelBackground.setLayout(new java.awt.BorderLayout());

        panelNorth.setMaximumSize(new java.awt.Dimension(1024, 62));
        panelNorth.setMinimumSize(new java.awt.Dimension(1024, 62));
        panelNorth.setPreferredSize(new java.awt.Dimension(1024, 62));
        panelNorth.setSize(new java.awt.Dimension(1024, 62));

        jLabel1.setFont(new java.awt.Font("Optima", 1, 24)); // NOI18N
        jLabel1.setText("AddEmployeeFrame");
        panelNorth.add(jLabel1);

        panelBackground.add(panelNorth, java.awt.BorderLayout.NORTH);

        panelCenter.setMaximumSize(new java.awt.Dimension(1024, 582));
        panelCenter.setMinimumSize(new java.awt.Dimension(1024, 582));
        panelCenter.setPreferredSize(new java.awt.Dimension(1024, 582));
        panelCenter.setSize(new java.awt.Dimension(1024, 582));
        panelCenter.setLayout(new java.awt.BorderLayout());

        panelCenterLeft.setPreferredSize(new java.awt.Dimension(425, 690));
        panelCenterLeft.setLayout(new javax.swing.BoxLayout(panelCenterLeft, javax.swing.BoxLayout.LINE_AXIS));

        tableLeft.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Fornavn", "Etternavn", "Sist reg", "Ant uten"
            }
        ));
        tableNotAttending.setViewportView(tableLeft);

        panelCenterLeft.add(tableNotAttending);

        panelCenter.add(panelCenterLeft, java.awt.BorderLayout.WEST);

        panelCenterCenter.setPreferredSize(new java.awt.Dimension(174, 690));

        buttonAddToCase.setFont(new java.awt.Font("Optima", 1, 18)); // NOI18N
        buttonAddToCase.setText("->");
        buttonAddToCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddToCaseActionPerformed(evt);
            }
        });

        buttonRemoveFromCase.setFont(new java.awt.Font("Optima", 1, 18)); // NOI18N
        buttonRemoveFromCase.setText("<-");
        buttonRemoveFromCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveFromCaseActionPerformed(evt);
            }
        });

        buttonFinish.setFont(new java.awt.Font("Optima", 1, 18)); // NOI18N
        buttonFinish.setText("Ferdig");
        buttonFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFinishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCenterCenterLayout = new javax.swing.GroupLayout(panelCenterCenter);
        panelCenterCenter.setLayout(panelCenterCenterLayout);
        panelCenterCenterLayout.setHorizontalGroup(
            panelCenterCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCenterCenterLayout.createSequentialGroup()
                .addGroup(panelCenterCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCenterCenterLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(panelCenterCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonAddToCase, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonRemoveFromCase, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelCenterCenterLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(buttonFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
        );
        panelCenterCenterLayout.setVerticalGroup(
            panelCenterCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCenterCenterLayout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(buttonAddToCase, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonRemoveFromCase, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelCenter.add(panelCenterCenter, java.awt.BorderLayout.CENTER);

        panelCenterRight.setPreferredSize(new java.awt.Dimension(425, 690));
        panelCenterRight.setLayout(new javax.swing.BoxLayout(panelCenterRight, javax.swing.BoxLayout.LINE_AXIS));

        tableRight.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Fornavn", "Etternavn", "Sist reg", "Ant uten"
            }
        ));
        tableAttending.setViewportView(tableRight);

        panelCenterRight.add(tableAttending);

        panelCenter.add(panelCenterRight, java.awt.BorderLayout.EAST);

        panelBackground.add(panelCenter, java.awt.BorderLayout.CENTER);

        panelSouth.setBackground(new java.awt.Color(153, 153, 153));
        panelSouth.setMaximumSize(new java.awt.Dimension(1024, 62));
        panelSouth.setMinimumSize(new java.awt.Dimension(1024, 62));
        panelSouth.setPreferredSize(new java.awt.Dimension(1024, 62));
        panelSouth.setSize(new java.awt.Dimension(1024, 62));

        javax.swing.GroupLayout panelSouthLayout = new javax.swing.GroupLayout(panelSouth);
        panelSouth.setLayout(panelSouthLayout);
        panelSouthLayout.setHorizontalGroup(
            panelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        panelSouthLayout.setVerticalGroup(
            panelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        panelBackground.add(panelSouth, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 706, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddToCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddToCaseActionPerformed
        try{
            int employeeId = (int)tableLeft.getValueAt(tableLeft.getSelectedRow(), 0);        
            employees.addToCase(caseId, employeeId);  
            employees.setAntUtenZero(employeeId);        
            employees.updateEmployeeAvailable(tableLeft, tableRight, caseId);
        }catch(ArrayIndexOutOfBoundsException e){
            showMessageDialog(null, "Vennligst velg en arbeider"); 
        }
    }//GEN-LAST:event_buttonAddToCaseActionPerformed

    private void buttonRemoveFromCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveFromCaseActionPerformed
        try{
            int employeeId = (int)tableRight.getValueAt(tableRight.getSelectedRow(), 0);        
            employees.removeFromCase(caseId, employeeId);  
            employees.resetAntUten(employeeId);
            employees.updateEmployeeAvailable(tableLeft, tableRight, caseId);
        }catch(ArrayIndexOutOfBoundsException e){
            showMessageDialog(null, "Vennligst velg en arbeider");
        }
    }//GEN-LAST:event_buttonRemoveFromCaseActionPerformed

    private void buttonFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFinishActionPerformed
         this.dispose();
    }//GEN-LAST:event_buttonFinishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(final int caseId) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addEmployeeFrame(caseId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddToCase;
    private javax.swing.JButton buttonFinish;
    private javax.swing.JButton buttonRemoveFromCase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelCenterCenter;
    private javax.swing.JPanel panelCenterLeft;
    private javax.swing.JPanel panelCenterRight;
    private javax.swing.JPanel panelNorth;
    private javax.swing.JPanel panelSouth;
    private javax.swing.JScrollPane tableAttending;
    private javax.swing.JTable tableLeft;
    private javax.swing.JScrollPane tableNotAttending;
    private javax.swing.JTable tableRight;
    // End of variables declaration//GEN-END:variables
}
