/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package frontend;

import backend.*;
import java.util.*;
import frontend.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author borgarlie
 */
public class DetailedView extends javax.swing.JFrame {
    
    private DateFormat formatter;
    private Date req_date;
    private Date checkup_date;
    private Date startDate;
    
    private Cases cases;
    private Users users;
    private Case currentCase;
    public static DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    public static Calendar today = Calendar.getInstance();

    /**
     * Creates new form DetailedView
     */
    public DetailedView(Case currentCase) {
        this.cases = new Cases();
        this.users = new Users();
        this.currentCase = currentCase;
        this.formatter = new SimpleDateFormat("dd-MM-yy");
        // format reqDate
        if(!this.currentCase.getReqDate().trim().equals("")) {
            try {
                this.req_date = this.formatter.parse(this.currentCase.getReqDate());
            } catch(Exception e) {
                System.out.println("ERROR in parse date");
            }
        }
        else {
            this.req_date = null;
        }
        // format checkupdate
        if(!this.currentCase.getReqDate().trim().equals("")) {
            try {
                this.checkup_date = this.formatter.parse(this.currentCase.getCheckup_date());
            } catch(Exception e) {
                System.out.println("ERROR in parse date");
            }
        }
        else {
            this.checkup_date = null;
        }
        if(!this.currentCase.getReqDate().trim().equals("")) {
            try {
                this.startDate = this.formatter.parse(this.currentCase.getStartDate());
            } catch(Exception e) {
                System.out.println("ERROR in parse date");
            }
        }
        else {
            // something else?
            this.startDate = null;
        }
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelCreateCaseDInspectDate = new javax.swing.JLabel();
        labelDContacts = new javax.swing.JLabel();
        labelCreateCaseDReqTime = new javax.swing.JLabel();
        labelCreateCaseDSupervisorHeader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDescription = new javax.swing.JTextArea();
        textFieldAddress = new javax.swing.JTextField();
        dateFieldStartDate = new com.toedter.calendar.JDateChooser();
        labelCreateCaseDNameHeader = new javax.swing.JLabel();
        textFieldPostPlace = new javax.swing.JTextField();
        textFieldPostalCode = new javax.swing.JTextField();
        labelDPostalCode = new javax.swing.JLabel();
        comboBoxStatus = new javax.swing.JComboBox();
        textFieldPhone = new javax.swing.JTextField();
        dateFieldReqDate = new com.toedter.calendar.JDateChooser();
        labelCustomerDFirstName = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        textFieldCustomerLastName = new javax.swing.JTextField();
        labelDPrice = new javax.swing.JLabel();
        textFieldCustomerFirstName = new javax.swing.JTextField();
        buttonComplete = new javax.swing.JButton();
        labelDEquipment = new javax.swing.JLabel();
        labelDDate = new javax.swing.JLabel();
        labelDAddress = new javax.swing.JLabel();
        labelCustomerDLastName = new javax.swing.JLabel();
        labelDDescription = new javax.swing.JLabel();
        dateFieldInspectDate = new com.toedter.calendar.JDateChooser();
        labelDStatus = new javax.swing.JLabel();
        textFieldSubject = new javax.swing.JTextField();
        labelDStartDate = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        textAreaContacts = new javax.swing.JTextArea();
        textFieldPrice = new javax.swing.JTextField();
        labelDSubject = new javax.swing.JLabel();
        labelCreateCaseName = new javax.swing.JLabel();
        labelDPhone = new javax.swing.JLabel();
        ComboBoxCreateCaseReqTime = new javax.swing.JComboBox();
        labelDReqDate = new javax.swing.JLabel();
        comboBoxCreateCaseSupervisor = new javax.swing.JComboBox();
        jScrollPane8 = new javax.swing.JScrollPane();
        textAreaToolList = new javax.swing.JTextArea();
        labelCreateCaseHeader = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 706));
        setPreferredSize(new java.awt.Dimension(1024, 706));

        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 706));

        labelCreateCaseDInspectDate.setText("Befaring: ");

        labelDContacts.setText("Kontaktpersoner");

        labelCreateCaseDReqTime.setText("Kl");

        labelCreateCaseDSupervisorHeader.setText("Utføres av");

        textAreaDescription.setColumns(20);
        textAreaDescription.setRows(5);
        textAreaDescription.setText(this.currentCase.getDescription());
        jScrollPane1.setViewportView(textAreaDescription);

        /* limit for hvor mange characters som kan skrives inn */
        textFieldAddress.setDocument(new JTextFieldLimit(30)); // endre tallet for å endre limit
        textFieldAddress.setText(this.currentCase.getAddress());
        textFieldAddress.setToolTipText("...");
        textFieldAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldAddressActionPerformed(evt);
            }
        });

        dateFieldStartDate.setDate(this.startDate);

        labelCreateCaseDNameHeader.setText("Mottatt av");

        textFieldPostPlace.setText(this.currentCase.getPostPlace());
        textFieldPostPlace.setToolTipText("...");
        textFieldPostPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldPostPlaceActionPerformed(evt);
            }
        });

        /* limit for hvor mange characters som kan skrives inn */
        textFieldPostalCode.setDocument(new JTextFieldLimit(4)); // endre tallet for å endre limit
        textFieldPostalCode.setText("" + this.currentCase.getPostalCode());
        textFieldPostalCode.setToolTipText("...");
        textFieldPostalCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldPostalCodeActionPerformed(evt);
            }
        });
        textFieldPostalCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldPostalCodeFocusLost(evt);
            }
        });
        textFieldPostalCode.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                textFieldPostalCodeInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        textFieldPostalCode.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                textFieldPostalCodePropertyChange(evt);
            }
        });

        labelDPostalCode.setText("Postnr");

        comboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Uferdig", "Aktiv", "Ferdig" }));

        /* limit for hvor mange characters som kan skrives inn */
        textFieldPhone.setDocument(new JTextFieldLimit(8)); // endre tallet for å endre limit
        textFieldPhone.setText("" + this.currentCase.getEmployer().getPhoneNumber());
        textFieldPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldPhoneActionPerformed(evt);
            }
        });

        dateFieldReqDate.setDate(this.req_date);

        labelCustomerDFirstName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCustomerDFirstName.setText("Kunde");

        labelDate.setText("fuck this shit..");

        /* limit for hvor mange characters som kan skrives inn */
        textFieldCustomerLastName.setDocument(new JTextFieldLimit(12)); // endre tallet for å endre limit
        textFieldCustomerLastName.setText(this.currentCase.getEmployer().getLastname());
        textFieldCustomerLastName.setToolTipText("");
        textFieldCustomerLastName.setVerifyInputWhenFocusTarget(false);
        textFieldCustomerLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCustomerLastNameActionPerformed(evt);
            }
        });

        labelDPrice.setText("Pris:");

        /* limit for hvor mange characters som kan skrives inn */
        textFieldCustomerFirstName.setDocument(new JTextFieldLimit(12)); // endre tallet for å endre limit
        textFieldCustomerFirstName.setText(this.currentCase.getEmployer().getFirstname());
        textFieldCustomerFirstName.setToolTipText("");
        textFieldCustomerFirstName.setVerifyInputWhenFocusTarget(false);
        textFieldCustomerFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCustomerFirstNameActionPerformed(evt);
            }
        });

        buttonComplete.setBackground(new java.awt.Color(0, 153, 51));
        buttonComplete.setText("Oppdater info");
        buttonComplete.setToolTipText("");
        buttonComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCompleteActionPerformed(evt);
            }
        });

        labelDEquipment.setText("Utstyrsliste");

        labelDDate.setText("Dato");

        labelDAddress.setText("Adresse");

        labelCustomerDLastName.setText("Etternavn");

        labelDDescription.setText("Beskrivelse / Annet");

        dateFieldInspectDate.setDate(this.checkup_date);

        labelDStatus.setText("Status");

        /* limit for hvor mange characters som kan skrives inn */
        textFieldSubject.setDocument(new JTextFieldLimit(30)); // endre tallet for å endre limit
        textFieldSubject.setText(this.currentCase.getSubject());
        textFieldSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldSubjectActionPerformed(evt);
            }
        });

        labelDStartDate.setText("Avtalt oppstart");

        textAreaContacts.setColumns(20);
        textAreaContacts.setRows(5);
        textAreaContacts.setText(this.currentCase.getContactPerson());
        jScrollPane7.setViewportView(textAreaContacts);

        /* limit for hvor mange characters som kan skrives inn */
        textFieldPrice.setDocument(new JTextFieldLimit(6)); // endre tallet for å endre limit
        textFieldPrice.setText("" + this.currentCase.getPrice());
        textFieldPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldPriceActionPerformed(evt);
            }
        });

        labelDSubject.setText("Arbeidets art");

        labelCreateCaseName.setText(this.users.getUserById(this.currentCase.getCreatorId()).toString());

        labelDPhone.setText("Telefon:");

        String[] tider = new String[48];
        int teller = 0;
        String time = "";
        String minutt = "";
        for(int i = 0; i<24; i++){
            for(int j = 0; j<31; j+=30){
                time = String.valueOf(i);
                if(i<10){
                    time ="0"+time;
                }
                minutt = String.valueOf(j);
                if(j==0){
                    minutt += "0";
                }
                tider[teller] = time + ":" + minutt;
                teller++;
            }
        }
        ComboBoxCreateCaseReqTime.setModel(new javax.swing.DefaultComboBoxModel(tider));
        ComboBoxCreateCaseReqTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxCreateCaseReqTimeActionPerformed(evt);
            }
        });

        labelDReqDate.setText("Ønsket oppstart");

        comboBoxCreateCaseSupervisor.setModel(new javax.swing.DefaultComboBoxModel(this.users.getUsers()));

        // borgar mix, skal finne en id som stemmer overens med combo box ut i fra database, works?

        ComboBoxModel model = comboBoxCreateCaseSupervisor.getModel();

        int size = model.getSize();
        boolean found = false;

        for (int i = 0; i < size; i++) {
            System.out.println("HHHEEELLLO");
            // instanceof?
            String tempStringUser = (String)model.getElementAt(i);
            System.out.println(tempStringUser + " " + this.users.getUserIdByFullName(tempStringUser));

            int tempUserId = this.users.getUserIdByFullName(tempStringUser);
            if(tempUserId == this.currentCase.getSupervisorId()) {
                System.out.println("I DONT WANT TO LIVE IN THIS WORLD");
                found = true;
                comboBoxCreateCaseSupervisor.setSelectedIndex(i
        );
                i = size;
            }
        }

        if(!found) {
            comboBoxCreateCaseSupervisor.setSelectedIndex(-1
        );
        }

        
        comboBoxCreateCaseSupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCreateCaseSupervisorActionPerformed(evt);
            }
        });

        textAreaToolList.setDocument(new JTextFieldLimit(100));
        textAreaToolList.setColumns(20);
        textAreaToolList.setRows(5);
        textAreaToolList.setText(this.currentCase.getToolList());
        jScrollPane8.setViewportView(textAreaToolList);

        labelCreateCaseHeader.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        labelCreateCaseHeader.setText("Detaljer Sak nr: " + this.currentCase.getId());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(422, Short.MAX_VALUE)
                .addComponent(labelCreateCaseHeader)
                .addGap(444, 444, 444))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelCreateCaseDNameHeader)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(labelDDate)))
                            .addGap(16, 16, 16)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelCreateCaseName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelDate))
                            .addGap(240, 240, 240)
                            .addComponent(labelCreateCaseDSupervisorHeader)
                            .addGap(6, 6, 6)
                            .addComponent(comboBoxCreateCaseSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(labelCustomerDFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(textFieldCustomerFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(60, 60, 60)
                                    .addComponent(textFieldCustomerLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(labelCustomerDLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(110, 110, 110)
                            .addComponent(labelDPrice)
                            .addGap(3, 3, 3)
                            .addComponent(textFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addComponent(labelDAddress)
                            .addGap(5, 5, 5)
                            .addComponent(textFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(85, 85, 85)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(60, 60, 60)
                                    .addComponent(dateFieldInspectDate, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(labelCreateCaseDInspectDate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addComponent(labelDPostalCode)
                            .addGap(5, 5, 5)
                            .addComponent(textFieldPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(textFieldPostPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addComponent(labelDPhone)
                            .addGap(4, 4, 4)
                            .addComponent(textFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(45, 45, 45)
                            .addComponent(labelDStartDate)
                            .addGap(6, 6, 6)
                            .addComponent(dateFieldStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(labelDSubject))
                                .addComponent(labelDReqDate))
                            .addGap(3, 3, 3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textFieldSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addComponent(dateFieldReqDate, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(labelCreateCaseDReqTime, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(ComboBoxCreateCaseReqTime, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(65, 65, 65)
                            .addComponent(labelDEquipment)
                            .addGap(8, 8, 8)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(labelDDescription)
                            .addGap(8, 8, 8)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(labelDContacts)
                                    .addGap(6, 6, 6)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(50, 50, 50)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(50, 50, 50)
                                            .addComponent(comboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(labelDStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(620, 620, 620)
                            .addComponent(buttonComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelCreateCaseHeader)
                .addContainerGap(658, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(labelCreateCaseDNameHeader)
                            .addGap(4, 4, 4)
                            .addComponent(labelDDate))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(labelCreateCaseName)
                            .addGap(4, 4, 4)
                            .addComponent(labelDate))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelCreateCaseDSupervisorHeader)
                                .addComponent(comboBoxCreateCaseSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(33, 33, 33)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelCustomerDFirstName)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(textFieldCustomerFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(textFieldCustomerLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelCustomerDLastName)
                        .addComponent(labelDPrice)
                        .addComponent(textFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(1, 1, 1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelDAddress)
                        .addComponent(textFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateFieldInspectDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelCreateCaseDInspectDate))
                    .addGap(6, 6, 6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(labelDPostalCode))
                        .addComponent(textFieldPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textFieldPostPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(6, 6, 6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(labelDPhone))
                        .addComponent(textFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(labelDStartDate))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(dateFieldStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(22, 22, 22)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(labelDSubject)
                            .addGap(14, 14, 14)
                            .addComponent(labelDReqDate))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(textFieldSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dateFieldReqDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelCreateCaseDReqTime)
                                .addComponent(ComboBoxCreateCaseReqTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(labelDEquipment)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelDContacts)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(70, 70, 70)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(comboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelDStatus)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelDDescription)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(20, 20, 20)
                    .addComponent(buttonComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldAddressActionPerformed

    private void textFieldPostPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldPostPlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldPostPlaceActionPerformed

    private void textFieldPostalCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldPostalCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldPostalCodeActionPerformed

    private void textFieldPostalCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldPostalCodeFocusLost
        // TODO add your handling code here:
        textFieldPostPlace.setText(textFieldPostalCode.getText());
        // set Field ut i fra postnr = poststed i database!!!
    }//GEN-LAST:event_textFieldPostalCodeFocusLost

    private void textFieldPostalCodeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_textFieldPostalCodeInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldPostalCodeInputMethodTextChanged

    private void textFieldPostalCodePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_textFieldPostalCodePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldPostalCodePropertyChange

    private void textFieldPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldPhoneActionPerformed

    private void textFieldCustomerLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCustomerLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCustomerLastNameActionPerformed

    private void textFieldCustomerFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCustomerFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCustomerFirstNameActionPerformed

    private void buttonCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCompleteActionPerformed
        Date reqDate = dateFieldReqDate.getDate();
        Date inspectDate = dateFieldInspectDate.getDate();
        Date startDate = dateFieldStartDate.getDate();

        String reqDateString = String.format("%1$td-%1$tm-%1$tY", reqDate);
        String inspectDateString = String.format("%1$td-%1$tm-%1$tY", inspectDate);
        String startDateString = String.format("%1$td-%1$tm-%1$tY", startDate);

        ArrayList<Integer> errors = this.cases.createCase(
            users.currentUser.getId(),
            textFieldCustomerFirstName.getText().trim(),
            textFieldCustomerLastName.getText().trim(),
            textFieldAddress.getText().trim(),
            textFieldPostalCode.getText().trim(),
            textFieldPostPlace.getText().trim(),
            textFieldPhone.getText().trim(),
            textFieldSubject.getText().trim(),
            reqDateString,
            ComboBoxCreateCaseReqTime.getSelectedItem().toString(),
            textAreaDescription.getText().trim(),
            this.users.getUserIdByFullName(comboBoxCreateCaseSupervisor.getSelectedItem().toString()),
            textFieldPrice.getText().trim(),
            inspectDateString,
            startDateString,
            textAreaToolList.getText().trim(),
            textAreaContacts.getText().trim(),
            comboBoxStatus.getSelectedItem().toString()
        );

        labelCustomerDFirstName.setForeground(Color.black);
        labelCustomerDLastName.setForeground(Color.black);
        // labelCustomerDFirstName.setForeground(Color.red);
        labelDSubject.setForeground(Color.black);
        labelDPhone.setForeground(Color.black);
        labelDPostalCode.setForeground(Color.black);
        labelDPrice.setForeground(Color.black);
        setErrors(errors);
        }

        public void setErrors(ArrayList<Integer> errors){
            for(Integer i : errors){
                if(i == Cases.NO_CONTRACTOR_FIRSTNAME){
                    labelCustomerDFirstName.setForeground(Color.red);
                }
                if(i == Cases.NO_CONTRACTOR_LASTNAME){
                    labelCustomerDLastName.setForeground(Color.red);
                }
                if(i == Cases.NO_CONTACT_INFO){
                    // labelCustomerDFirstName.setForeground(Color.red);
                }
                if(i == Cases.NO_SUBJECT){
                    labelDSubject.setForeground(Color.red);
                }
                if(i == Cases.WRONG_PHONE_FORMAT){
                    labelDPhone.setForeground(Color.red);
                }
                if(i == Cases.WRONG_POSTALCODE_FORMAT){
                    labelDPostalCode.setForeground(Color.red);
                }
                if(i == Cases.WRONG_PRICE_FORMAT){
                    labelDPrice.setForeground(Color.red);
                }
            }
    }//GEN-LAST:event_buttonCompleteActionPerformed

    private void textFieldSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldSubjectActionPerformed

    private void textFieldPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldPriceActionPerformed

    private void ComboBoxCreateCaseReqTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxCreateCaseReqTimeActionPerformed
        System.out.println(ComboBoxCreateCaseReqTime.getSelectedItem());        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxCreateCaseReqTimeActionPerformed

    private void comboBoxCreateCaseSupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCreateCaseSupervisorActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxCreateCaseSupervisorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(final Case currentCase) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailedView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailedView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailedView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailedView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailedView(currentCase).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBoxCreateCaseReqTime;
    private javax.swing.JButton buttonComplete;
    private javax.swing.JComboBox comboBoxCreateCaseSupervisor;
    private javax.swing.JComboBox comboBoxStatus;
    private com.toedter.calendar.JDateChooser dateFieldInspectDate;
    private com.toedter.calendar.JDateChooser dateFieldReqDate;
    private com.toedter.calendar.JDateChooser dateFieldStartDate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel labelCreateCaseDInspectDate;
    private javax.swing.JLabel labelCreateCaseDNameHeader;
    private javax.swing.JLabel labelCreateCaseDReqTime;
    private javax.swing.JLabel labelCreateCaseDSupervisorHeader;
    private javax.swing.JLabel labelCreateCaseHeader;
    private javax.swing.JLabel labelCreateCaseName;
    private javax.swing.JLabel labelCustomerDFirstName;
    private javax.swing.JLabel labelCustomerDLastName;
    private javax.swing.JLabel labelDAddress;
    private javax.swing.JLabel labelDContacts;
    private javax.swing.JLabel labelDDate;
    private javax.swing.JLabel labelDDescription;
    private javax.swing.JLabel labelDEquipment;
    private javax.swing.JLabel labelDPhone;
    private javax.swing.JLabel labelDPostalCode;
    private javax.swing.JLabel labelDPrice;
    private javax.swing.JLabel labelDReqDate;
    private javax.swing.JLabel labelDStartDate;
    private javax.swing.JLabel labelDStatus;
    private javax.swing.JLabel labelDSubject;
    private javax.swing.JLabel labelDate;
    private javax.swing.JTextArea textAreaContacts;
    private javax.swing.JTextArea textAreaDescription;
    private javax.swing.JTextArea textAreaToolList;
    private javax.swing.JTextField textFieldAddress;
    private javax.swing.JTextField textFieldCustomerFirstName;
    private javax.swing.JTextField textFieldCustomerLastName;
    private javax.swing.JTextField textFieldPhone;
    private javax.swing.JTextField textFieldPostPlace;
    private javax.swing.JTextField textFieldPostalCode;
    private javax.swing.JTextField textFieldPrice;
    private javax.swing.JTextField textFieldSubject;
    // End of variables declaration//GEN-END:variables
}