/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package frontend;

import backend.*;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jorgen
 */
public class ViewActiveTab extends javax.swing.JPanel {     
    private Cases cases; 
    private Users users;
    private addEmployeeFrame addEmployeeFrame;  
    private Employees employees;
    /**
     * Creates new form ViewActiveTab
     */
    public ViewActiveTab() {
        initComponents();
        panelCalender.setVisible(false);
        panelTableView.setVisible(true);
        this.cases = new Cases();
        this.users = new Users();
        this.employees = new Employees();
    }
    
    public void updateList(){    
    DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
    model.setRowCount(0);
    Object[] insertTable = new Object[4];
    this.cases.updateCaseList("Aktiv");

    for(int i = 0; i<this.cases.getCases().size(); i++){
        insertTable[0] = this.cases.getCases().get(i).getId();
        insertTable[1] = this.cases.getCases().get(i).getSubject();
        insertTable[2] = this.cases.getCases().get(i).getStartDate();
        insertTable[3] = this.users.getUserById(this.cases.getCases().get(i).getSupervisorId()).toString();
        model.insertRow(jTable2.getRowCount(), insertTable);                     
       }    
    }
    
    
    public JTable getTable(){
        return jTable2;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonAddEmployee = new javax.swing.JButton();
        panelTableView = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        panelCalender = new javax.swing.JPanel();
        buttonToggle1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));
        setLayout(null);

        buttonAddEmployee.setText("Legg til arbeidere");
        buttonAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddEmployeeActionPerformed(evt);
            }
        });
        add(buttonAddEmployee);
        buttonAddEmployee.setBounds(520, 610, 234, 41);

        panelTableView.setBackground(new java.awt.Color(255, 255, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Saksnummer", "Emne", "Utførelsesdato", "Ansvarlig"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMinWidth(80);
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTable2.getColumnModel().getColumn(0).setMaxWidth(80);
            jTable2.getColumnModel().getColumn(2).setMinWidth(140);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(140);
            jTable2.getColumnModel().getColumn(2).setMaxWidth(140);
        }

        javax.swing.GroupLayout panelTableViewLayout = new javax.swing.GroupLayout(panelTableView);
        panelTableView.setLayout(panelTableViewLayout);
        panelTableViewLayout.setHorizontalGroup(
            panelTableViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        panelTableViewLayout.setVerticalGroup(
            panelTableViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        add(panelTableView);
        panelTableView.setBounds(0, 0, 1024, 600);

        panelCalender.setBackground(new java.awt.Color(102, 255, 102));

        javax.swing.GroupLayout panelCalenderLayout = new javax.swing.GroupLayout(panelCalender);
        panelCalender.setLayout(panelCalenderLayout);
        panelCalenderLayout.setHorizontalGroup(
            panelCalenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        panelCalenderLayout.setVerticalGroup(
            panelCalenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        add(panelCalender);
        panelCalender.setBounds(-2, 1, 1030, 600);

        buttonToggle1.setText("Gå til kalender");
        buttonToggle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonToggle1ActionPerformed(evt);
            }
        });
        add(buttonToggle1);
        buttonToggle1.setBounds(784, 609, 234, 41);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddEmployeeActionPerformed
        int id = (int)jTable2.getValueAt(jTable2.getSelectedRow(), 0);
        this.addEmployeeFrame = new addEmployeeFrame(id);
        addEmployeeFrame.setVisible(true);
        this.employees.updateEmployeeAvailable(addEmployeeFrame.getTableLeft(), addEmployeeFrame.getTableRight(), id);
    }//GEN-LAST:event_buttonAddEmployeeActionPerformed

    private void buttonToggle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonToggle1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonToggle1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddEmployee;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonToggle1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel panelCalender;
    private javax.swing.JPanel panelTableView;
    // End of variables declaration//GEN-END:variables
}
