/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package frontend;

import backend.*;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jorgen
 */
public class ViewActiveTab extends javax.swing.JPanel {
    private Operator op;
     
     
    /**
     * Creates new form ViewActiveTab
     */
    public ViewActiveTab(Operator op) {
        initComponents();
        panelCalender.setVisible(false);
        panelTableView.setVisible(true);
        this.op = op;
    }
    
    public JTable getTable(){
        return jTable2;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonToggle = new javax.swing.JButton();
        panelTableView = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        panelCalender = new javax.swing.JPanel();

        setBackground(new java.awt.Color(153, 153, 153));
        setLayout(null);

        buttonToggle.setText("Gå til kalender");
        buttonToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonToggleActionPerformed(evt);
            }
        });
        add(buttonToggle);
        buttonToggle.setBounds(784, 609, 234, 41);

        panelTableView.setBackground(new java.awt.Color(255, 255, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Saksnummer", "Emne", "Utførelsesdato", "Ansvarlig"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMinWidth(80);
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTable2.getColumnModel().getColumn(0).setMaxWidth(80);
            jTable2.getColumnModel().getColumn(2).setMinWidth(140);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(140);
            jTable2.getColumnModel().getColumn(2).setMaxWidth(140);
        }

        javax.swing.GroupLayout panelTableViewLayout = new javax.swing.GroupLayout(panelTableView);
        panelTableView.setLayout(panelTableViewLayout);
        panelTableViewLayout.setHorizontalGroup(
            panelTableViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        panelTableViewLayout.setVerticalGroup(
            panelTableViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        add(panelTableView);
        panelTableView.setBounds(0, 0, 1024, 600);

        panelCalender.setBackground(new java.awt.Color(102, 255, 102));

        javax.swing.GroupLayout panelCalenderLayout = new javax.swing.GroupLayout(panelCalender);
        panelCalender.setLayout(panelCalenderLayout);
        panelCalenderLayout.setHorizontalGroup(
            panelCalenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        panelCalenderLayout.setVerticalGroup(
            panelCalenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        add(panelCalender);
        panelCalender.setBounds(-2, 1, 1030, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonToggleActionPerformed
        if (!panelCalender.isVisible()){
             panelTableView.setVisible(false);
             panelCalender.setVisible(true);
             buttonToggle.setText("Gå til Tabel");

        } else {
            
            panelCalender.setVisible(false);
            panelTableView.setVisible(true);
            buttonToggle.setText("Gå til Kalender");

        }
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_buttonToggleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonToggle;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel panelCalender;
    private javax.swing.JPanel panelTableView;
    // End of variables declaration//GEN-END:variables
}
